### ISSUE TITLE
VHook

### ISSUE THREAD

**Issue by HenrikThoroe** [Coronon/flyde#10]
# VHook

Don't get me wrong, it's a good tool. But for now it's lacking a few important functionalities and produces quite a bit overhead. 
Would be nice if you could improve on it. If you don't have time I could do it as well. 

Below I listed what I currently miss.

## Overhead

```dart
// Would be nice to combine expect and awaitValue methods
await hook.expect(equals(*), timeout: Duration(years: 42));

// For now we have to use a two-liner for this
await hook.awaitValue(Duration(years: 42));
hook.expect(equals(*));
```

## Functionality

- Have to use `bool?` if I only want to distinguish between two states. 
- No replacement for `Completer.completeError`
- If my value can be `null` I cannot await it
- I'd like to await based on the value and not be limited to `null` checks. For example `awaitValue(Duration(years: 42), (value) => condition)`

_Originally posted by @HenrikThoroe in https://github.com/Coronon/flyde/issues/9#issuecomment-914277597_

**Comment by HenrikThoroe** [comment]
# The behavior I'd like to get from VHook


## Discard need to make every awaitable hook optional

Also a default value is not always possible or makes sense. I'd suggest to use `late` and have a `_hasValue` flag present.
I recognize that an optional default parameter could be tricky when the default value of `null` is really required. The question is if no value wouldn't carry the same information. Open for discussion.

```dart 
// VHook([T? default])
final hook = VHook<int>();
```


## Completer like API including method to fail with an error

Would be more convenient for new devs as well. The `completeError` method would add value to `VHook`

```dart 
// void complete(T value)
hook.complete(0);

// void completeError(Exception exception) | or dynamic exception?
hook.completeError('Unfortunately 0 is not a number today. Try again tomorrow.');
```


## Method to set / modify the value without completing

Sometimes the value is important to really call the hook completed. Like when tracking active connections or any other counter.

```dart
// T update(T Function(T?));
hook.update((int? current) => current + 1 ?? 0);

// Future<T> updateAsync(Future<T> Function(T?));
hook.updateAsync((int? current) async => current + 1 ?? 0);

// void updateValue(T);
hook.updateValue(1);

// void finish();
// Completes the hook with the last value and skips possible handlers.
hook.finish();
```


## Method to await based on content

If no value handler is provided the future completes when the first value arrives from any update method. The `complete` method would skip the handler at all. 

The method should always throw on timeout. Maybe the timeout should be optional?
The return value is the value is a future of the value on which it completed.

```dart 
// Future<T> awaitValue(Duration timeout, [bool Function(T)? handler]);
hook.awaitValue(Duration(eternities: 66), (int value) => value > 2);
```


## Combined expect and await method

This method could be used instead of `awaitValue` to instantly apply a matcher on completion.

```dart 
// Future<T> expectAsync(Duration timeout, [Matcher? matcher]);
hook.expectAsync(Duration(eternities: 66), equals(3));
```

**Comment by Coronon** [comment]
'Basic' refactor with commit https://github.com/Coronon/flyde/commit/9c8ae6d6e5c32ac3f4436ab92dfa61db531842ef

- No requirement for values (no requirement for `null` nor optionals)
- Set value without completing (primitive `set(T val)`, updaters will be added soon)
- Await based on content (own conditions)
- Complete value
- Await completion

The other requested features will follow soon. I will also try to update all existing tests to the new `VHook`.

**Comment by Coronon** [comment]
Added updaters with https://github.com/Coronon/flyde/commit/73cbb4af1b6c4c7e27df27713a5d388fec7550cb

**Comment by Coronon** [comment]
Added error handling with https://github.com/Coronon/flyde/commit/aac46d3a5668813885e249d110475abd1978e979

Im not sure about the behaviour of `awaitValue` though:
If we already completed with an error and `awaitValue` is called, should we return the Future that contains the error or simply throw the error?

I would like to throw as this comes closes to the behaviour when we complete with an Error while awaiting a value through:
```dart
Future<T> awaitValue({Duration? timeout, bool Function(T)? condition}) async {
    // ...

    // Throw if already completed with error
    _assertNotCompletedError();                                         // <---------- BUT SHOULD WE?

    // ...

    // Subscribe to changes and find first that satisfies [condition]
    Future<dynamic> value = _stream.stream.firstWhere(wrappedCond);     // <---------- THIS WILL THROW ON ERROR!

    // ...
  }

**Comment by Coronon** [comment]
Added simpler matching with https://github.com/Coronon/flyde/commit/0e05c59356d06fcf382f5e4590b4e55deea17fcf and https://github.com/Coronon/flyde/commit/2e9c07c5a0d20bfab6188fb8cf87d691e4d9fcad

**Comment by HenrikThoroe** [comment]
> 
> 
> Added error handling with [aac46d3](https://github.com/Coronon/flyde/commit/aac46d3a5668813885e249d110475abd1978e979)
> 
> Im not sure about the behaviour of `awaitValue` though:
> If we already completed with an error and `awaitValue` is called, should we return the Future that contains the error or simply throw the error?
> 
> I would like to throw as this comes closes to the behaviour when we complete with an Error while awaiting a value through:
> 
> ```dart
> Future<T> awaitValue({Duration? timeout, bool Function(T)? condition}) async {
>     // ...
> 
>     // Throw if already completed with error
>     _assertNotCompletedError();                                         // <---------- BUT SHOULD WE?
> 
>     // ...
> 
>     // Subscribe to changes and find first that satisfies [condition]
>     Future<dynamic> value = _stream.stream.firstWhere(wrappedCond);     // <---------- THIS WILL THROW ON ERROR!
> 
>     // ...
>   }
> ```

Maybe I don't fully understand your question, but there is no difference between returning a future which completes with an error or throwing an error in an async function. Both returns a future which rejects. If I understood your code correctly `_asssertNoError` throws if the `Completer` object was called with `completeError` and `_stream` is called with `addError`. So both should throw the same error object, shouldn't they? The only difference would be possible side effect between those calls, otherwise the behavior would be the same.

**Comment by Coronon** [comment]
You are totally right, I was just wondering what would be nicer here. But we'll just stick to throwing.
